# dados.py

# Lista de todas as missas
# Para adicionar uma nova, basta copiar uma linha e alterar os dados.
MISSAS = [
    # --- DOMINGO ---
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São João Bosco", "Bairro": "Jd. das Indústrias", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Matriz São José", "Bairro": "Centro", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Nossa Senhora de Fátima", "Bairro": "Altos de Santana", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São Benedito", "Bairro": "Altos da Ponte", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São José Operário (Vila Paiva)", "Bairro": "V. Paiva", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santuário São Judas Tadeu", "Bairro": "Jd. Paulista", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São Sebastião", "Bairro": "Vl. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Nossa Senhora do Rosário", "Bairro": "Vl. Tesouro", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São Benedito (Galo Branco)", "Bairro": "Galo Branco", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Coração Eucarístico de Jesus", "Bairro": "Pq. Novo Horizonte", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santa Rita de Cássia", "Bairro": "Jd. da Granja", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santa Luzia", "Bairro": "Vl. Iracema", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santo Antônio (Paraibuna)", "Bairro": "Centro", "Cidade": "Paraibuna"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São Vicente de Paulo", "Bairro": "Jd. São Vicente", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santa Inês", "Bairro": "Jd. Santa Inês I", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Coração de Jesus", "Bairro": "Bosque dos Eucaliptos", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Nossa Senhora de Lourdes", "Bairro": "Pq. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Nossa Senhora do Perpétuo Socorro", "Bairro": "Campo dos Alemães", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Espírito Santo", "Bairro": "Jd. Satélite", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Nossa Senhora da Santíssima Trindade (Jacareí)", "Bairro": "Centro", "Cidade": "Jacareí"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santa Branca", "Bairro": "Centro", "Cidade": "Santa Branca"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santa Cecília (Jacareí)", "Bairro": "Centro", "Cidade": "Jacareí"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Nossa Senhora de Guadalupe (Jacareí)", "Bairro": "Jd. das Indústrias", "Cidade": "Jacareí"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São José Operário (Jacareí)", "Bairro": "Cidade Salvador", "Cidade": "Jacareí"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São João Batista (Jacareí)", "Bairro": "São João", "Cidade": "Jacareí"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São Paulo Apóstolo", "Bairro": "Jd. Nova Michigan", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "São José, Esposo de Maria", "Bairro": "Campos de São José", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:00", "Paroquia": "Santa Ana", "Bairro": "Santana", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "07:30", "Paroquia": "Nossa Senhora da Soledade", "Bairro": "Vista Verde", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "08:00", "Paroquia": "Santo Agostinho", "Bairro": "Urbanova V", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "08:00", "Paroquia": "Sagrada Família", "Bairro": "V. Ema", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "08:00", "Paroquia": "Catedral de São Dimas", "Bairro": "Jd. São Dimas", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "08:30", "Paroquia": "Coração de Jesus", "Bairro": "Bosque dos Eucaliptos", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "08:30", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "09:00", "Paroquia": "São João Bosco", "Bairro": "Jd. das Indústrias", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "09:00", "Paroquia": "Nossa Senhora de Fátima", "Bairro": "Altos de Santana", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "09:00", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "09:00", "Paroquia": "Nossa Senhora de Lourdes", "Bairro": "Pq. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "09:30", "Paroquia": "Coração Eucarístico de Jesus", "Bairro": "Pq. Novo Horizonte", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "09:30", "Paroquia": "Espírito Santo", "Bairro": "Jd. Satélite", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "10:00", "Paroquia": "Matriz São José", "Bairro": "Centro", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "10:00", "Paroquia": "Sagrada Família", "Bairro": "V. Ema", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "10:00", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "10:00", "Paroquia": "São Peregrino", "Bairro": "Jardim das Colinas", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "11:00", "Paroquia": "São João Bosco", "Bairro": "Jd. das Indústrias", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "11:00", "Paroquia": "Catedral de São Dimas", "Bairro": "Jd. São Dimas", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "11:00", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "11:00", "Paroquia": "Nossa Senhora de Lourdes", "Bairro": "Pq. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "12:00", "Paroquia": "Espírito Santo", "Bairro": "Jd. Satélite", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "15:00", "Paroquia": "Nossa Senhora de Lourdes", "Bairro": "Pq. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "15:00", "Paroquia": "Nossa Senhora do Perpétuo Socorro", "Bairro": "Campo dos Alemães", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "17:00", "Paroquia": "Sagrada Família", "Bairro": "V. Ema", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "17:00", "Paroquia": "Espírito Santo", "Bairro": "Jd. Satélite", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "17:00", "Paroquia": "Nossa Senhora de Lourdes", "Bairro": "Pq. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "18:00", "Paroquia": "Matriz São José", "Bairro": "Centro", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "18:00", "Paroquia": "São Peregrino", "Bairro": "Jardim das Colinas", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "18:00", "Paroquia": "Coração de Jesus", "Bairro": "Bosque dos Eucaliptos", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "19:00", "Paroquia": "Sagrada Família", "Bairro": "V. Ema", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "19:00", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "19:00", "Paroquia": "Nossa Senhora de Lourdes", "Bairro": "Pq. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "19:00", "Paroquia": "São João Bosco", "Bairro": "Jd. das Indústrias", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "19:30", "Paroquia": "Catedral de São Dimas", "Bairro": "Jd. São Dimas", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "19:30", "Paroquia": "Espírito Santo", "Bairro": "Jd. Satélite", "Cidade": "São José dos Campos"},
    {"Dia": "Domingo", "Horario": "19:30", "Paroquia": "Coração Eucarístico de Jesus", "Bairro": "Pq. Novo Horizonte", "Cidade": "São José dos Campos"},

    # --- DIAS DE SEMANA & SÁBADO (Mantendo alguns exemplos para funcionalidade) ---
    {"Dia": "Segunda-feira", "Horario": "07:00", "Paroquia": "Matriz São José", "Bairro": "Centro", "Cidade": "São José dos Campos"},
    {"Dia": "Segunda-feira", "Horario": "12:15", "Paroquia": "Catedral de São Dimas", "Bairro": "Jd. São Dimas", "Cidade": "São José dos Campos"},
    {"Dia": "Segunda-feira", "Horario": "19:30", "Paroquia": "Sagrada Família", "Bairro": "V. Ema", "Cidade": "São José dos Campos"},
    {"Dia": "Terça-feira", "Horario": "07:00", "Paroquia": "Catedral de São Dimas", "Bairro": "Jd. São Dimas", "Cidade": "São José dos Campos"},
    {"Dia": "Terça-feira", "Horario": "19:30", "Paroquia": "Espírito Santo", "Bairro": "Jd. Satélite", "Cidade": "São José dos Campos"},
    {"Dia": "Quarta-feira", "Horario": "07:00", "Paroquia": "Matriz São José", "Bairro": "Centro", "Cidade": "São José dos Campos"},
    {"Dia": "Quarta-feira", "Horario": "19:30", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"},
    {"Dia": "Quinta-feira", "Horario": "19:30", "Paroquia": "Catedral de São Dimas", "Bairro": "Jd. São Dimas", "Cidade": "São José dos Campos"},
    {"Dia": "Sexta-feira", "Horario": "12:15", "Paroquia": "Catedral de São Dimas", "Bairro": "Jd. São Dimas", "Cidade": "São José dos Campos"},
    {"Dia": "Sexta-feira", "Horario": "19:30", "Paroquia": "Nossa Senhora de Lourdes", "Bairro": "Pq. Industrial", "Cidade": "São José dos Campos"},
    {"Dia": "Sábado", "Horario": "07:00", "Paroquia": "Matriz São José", "Bairro": "Centro", "Cidade": "São José dos Campos"},
    {"Dia": "Sábado", "Horario": "18:00", "Paroquia": "Sagrada Família", "Bairro": "V. Ema", "Cidade": "São José dos Campos"},
    {"Dia": "Sábado", "Horario": "19:00", "Paroquia": "Espírito Santo", "Bairro": "Jd. Satélite", "Cidade": "São José dos Campos"},
    {"Dia": "Sábado", "Horario": "19:30", "Paroquia": "São Bento", "Bairro": "Jd. Morumbi", "Cidade": "São José dos Campos"}
    # ... (VOCÊ PODE COLAR O RESTANTE DA LISTA AQUI)
]